# Generated by Django 3.2.13 on 2022-06-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0019_allow_blank_minimum_change_request_approvals'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='expose_traits_to_clients',
            field=models.BooleanField(default=True),
        ),
    ]
